# --- Development image ---
FROM oven/bun:alpine AS dev

# Set working directory
WORKDIR /app

# Copy dependency file (for cache layer)
COPY bun.lock package.json ./

# Install dependency (dev deps included)
RUN bun install

# Copy source code
COPY . .

# Expose Nuxt default port
EXPOSE 3000

# Run Nuxt dev server
CMD ["bun", "run", "dev"]
